version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./employee-dashboard-backend
    ports:
      - "3000:3000"
    volumes:
      - ./employee-dashboard-backend:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=employeedb
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./employee-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./employee-dashboard:/app
    environment:
      - NODE_ENV=development
